server:
  port: 9004
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/bpm_db?characterEncoding=utf-8&useSSL=false
    driverClassName: com.mysql.jdbc.Driver
    username: root
    password: root
  activiti: #开启历史信息
    db-history-used: true
    #activiti会对所有表进行更新，不存在的情况会创建
    database-schema-update: true
    history-level: full