server:
  port: 9000

spring:
  application:
    name: gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: r_common
          uri: lb://kdcommon
          predicates:
            - Path=/**

eureka:
  instance:
    hostname: gateway
  client:
    service-url:
      defaultZone: http://localhost:9009/eureka/


