server:
  port: 9001
#虚拟机ip
vIP: 192.168.57.133

spring:
  application:
    name: kdcommon
  datasource:
    url: jdbc:mysql://localhost:3306/yinydb?characterEncoding=utf-8&useSSL=false&serverTimezone=UTC
    driverClassName: com.mysql.cj.jdbc.Driver
    username: root
    password: root
    # 使用druid数据源
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    filters: stat
    maxActive: 20
    initialSize: 1
    maxWait: 60000
    minIdle: 1
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: select 'x'
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    maxOpenPreparedStatements: 20
  redis:
    port: 6379
    host: ${vIP}
    lettuce:
      pool:
        max-active: 8
        max-idle: 8
        min-idle: 0
        max-wait: 1000ms
      shutdown-timeout: 100ms
  rabbitmq:
    username: yyh
    password: yyh123345
    virtual-host: /
    host: ${vIP}
    port: 5672

management:
  endpoint:
    nacos-discovery:
      enabled: true

eureka:
  client:
    service-url:
      defaultZone:
        http://localhost:9009/eureka/

#日志
logging:
  path: d:/log
  level:
    root: info
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl #开启sql日志
