server:
  port: 9000

spring:
  application:
    name: gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: r_common
          uri: lb://kdcommon
          predicates:
            - Path=/**
    nacos:
      discovery:
        server-addr: 175.178.192.58:8848

#eureka:
#  instance:
#    hostname: gateway
#  client:
#    service-url:
#      defaultZone: http://localhost:9009/eureka/

#nacos监控暴露
#management:
  endpoints:
    web:
      exposure:
        include: '*'

