server:
  port: 9002
#虚拟机ip
vIP: 192.168.57.133

spring:
  application:
    name: kdgateway
  #nacos注册
  cloud:
    nacos:
      discovery:
        server-addr: ${vIP}:28848

management:
  endpoint:
    nacos-discovery:
      enabled: true

#日志
logging:
  path: d:/log
  level:
    root: info

