server:
  port: 9004
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/bpm_db?characterEncoding=utf-8&useSSL=false
    driverClassName: com.mysql.jdbc.Driver
    username: root
    password: root
  activiti:
    db-history-used: true