server:
  port: 9006
#虚拟机ip
vIP: 175.178.192.58

spring:
  application:
    name: kdfounder
  cloud:
    nacos:
      discovery:
        server-addr: ${vIP}:8848


#设置超时时间
feign:
  client:
    config:
      default:
        connectTimeout: 3000
        readTimeout: 3000
