server:
  port: 9002
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/yinydb?characterEncoding=utf-8&useSSL=false
    driverClassName: com.mysql.jdbc.Driver
    username: root
    password: root

logging:
  path: d:/log
  level:
    root: info
mybatis:
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl