server:
  port: 9006

spring:
  application:
    name: kdfounder

eureka:
  instance:
    hostname: kdfounder
  client:
    service-url:
      defaultZone: http://localhost:9009/eureka/

#设置超时时间
feign:
  client:
    config:
      default:
        connectTimeout: 3000
        readTimeout: 3000
